---
defaultsConfigmap:
  annotations:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  timeoutMinutes: "180"

commonCR:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous

pipelines:
  repos:
    tooling:
      repoURL: https://github.com/ygalblum/rhel-edge-automation-arch.git
      targetRevision: httpd_repos_list
    blueprints:
      repoURL: https://github.com/ygalblum/rhel-edge-automation-arch.git
      targetRevision: blueprints
    kickstarts:
      repoURL: https://github.com/ygalblum/rhel-edge-automation-arch.git
      targetRevision: kickstarts
