rhel:
  version: "8.5"

imageDownloaderJob:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
  activeDeadlineSeconds: 600

ansibleVM:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
  activeDeadlineSeconds: 1800

imageBuilderVM:
  labels:
    app: image-builder
    workload.template.kubevirt.io/server: "true"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    description: RHEL 8 With Image Builder
  template:
    labels:
      kubevirt.io/domain: image-builder
      vm.kubevirt.io/name: image-builder
      workload.template.kubevirt.io/server: "true"
  machine:
    type: pc-q35-rhel8.4.0
  cores: 8
  memory: 16Gi
  composer:
    sources: []

gitRepository: https://github.com/ygalblum/rhel-edge-automation-arch.git
gitBranch: httpd_repos_list
